// RUN: xt-opt --xt-serialize %s | FileCheck %s

func.func @serialize_grid(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.grid = array<i32: 2, 2, 1>} {
  %bid0:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %bid1:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid0#0, %bid1#1) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  %1 = "xt.exp"(%0) : (tensor<16x16xf32>) -> tensor<16x16xf32>
  "xt.store"(%1, %dst, %bid1#0, %bid0#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

func.func @serialize_shared_x(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.grid = array<i32: 2, 2, 1>} {
  %bid:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid#0, %bid#1) <{shared = 1 : i64}> : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  "xt.store"(%0, %dst, %bid#0, %bid#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

func.func @serialize_shared_xy(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.grid = array<i32: 2, 2, 2>} {
  %bid:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid#0, %bid#1) <{shared = 2 : i64}> : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  "xt.store"(%0, %dst, %bid#0, %bid#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

func.func @serialize_double_buffer_x(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.double_buffering = 1 : i32, xt.grid = array<i32: 2, 1, 1>} {
  %bid:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid#0, %bid#1) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  "xt.store"(%0, %dst, %bid#0, %bid#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

func.func @serialize_double_buffer_shared_x(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.double_buffering = 1 : i32, xt.grid = array<i32: 2, 2, 1>} {
  %bid:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid#0, %bid#1) <{shared = 1 : i64}> : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  "xt.store"(%0, %dst, %bid#0, %bid#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

func.func @serialize_double_buffer_shared_xy(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.double_buffering = 1 : i32, xt.grid = array<i32: 2, 2, 2>} {
  %bid:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid#0, %bid#1) <{shared = 2 : i64}> : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  "xt.store"(%0, %dst, %bid#0, %bid#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

func.func @serialize_double_buffer_store_value(%src: memref<128x16xf32>, %dst: memref<128x16xf32>) attributes {xt.double_buffering = 1 : i32, xt.grid = array<i32: 2, 1, 1>} {
  %bid:3 = "xt.get_tile_block_id"() : () -> (i32, i32, i32)
  %0 = "xt.load"(%src, %bid#0, %bid#1) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
  %1 = "xt.exp"(%0) : (tensor<16x16xf32>) -> tensor<16x16xf32>
  "xt.store"(%1, %dst, %bid#0, %bid#1) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
  func.return
}

// CHECK-LABEL: func.func @serialize_grid
// CHECK-NOT: xt.get_tile_block_id
// CHECK: %[[X00:.*]] = arith.constant 0 : i32
// CHECK: %[[Y00:.*]] = arith.constant 0 : i32
// CHECK: %[[Z00:.*]] = arith.constant 0 : i32
// CHECK: xt.load(%arg0, %[[X00]], %[[Y00]])
// CHECK: xt.store(%{{.*}}, %arg1, %[[X00]], %[[Y00]])
// CHECK: %[[X10:.*]] = arith.constant 1 : i32
// CHECK: %[[Y10:.*]] = arith.constant 0 : i32
// CHECK: %[[Z10:.*]] = arith.constant 0 : i32
// CHECK: xt.load(%arg0, %[[X10]], %[[Y10]])
// CHECK: xt.store(%{{.*}}, %arg1, %[[X10]], %[[Y10]])
// CHECK: %[[X01:.*]] = arith.constant 0 : i32
// CHECK: %[[Y01:.*]] = arith.constant 1 : i32
// CHECK: %[[Z01:.*]] = arith.constant 0 : i32
// CHECK: xt.load(%arg0, %[[X01]], %[[Y01]])
// CHECK: xt.store(%{{.*}}, %arg1, %[[X01]], %[[Y01]])
// CHECK: %[[X11:.*]] = arith.constant 1 : i32
// CHECK: %[[Y11:.*]] = arith.constant 1 : i32
// CHECK: %[[Z11:.*]] = arith.constant 0 : i32
// CHECK: xt.load(%arg0, %[[X11]], %[[Y11]])
// CHECK: xt.store(%{{.*}}, %arg1, %[[X11]], %[[Y11]])

// CHECK-LABEL: func.func @serialize_shared_x
// CHECK-NOT: xt.get_tile_block_id
// CHECK: %[[SX0:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 1 : i64}
// CHECK: xt.store(%[[SX0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SX0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: %[[SX1:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 1 : i64}
// CHECK: xt.store(%[[SX1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SX1]], %arg1, %{{.*}}, %{{.*}})

// CHECK-LABEL: func.func @serialize_shared_xy
// CHECK-NOT: xt.get_tile_block_id
// CHECK: %[[SXY0:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 2 : i64}
// CHECK: xt.store(%[[SXY0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SXY0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SXY0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SXY0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: %[[SXY1:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 2 : i64}
// CHECK: xt.store(%[[SXY1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SXY1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SXY1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[SXY1]], %arg1, %{{.*}}, %{{.*}})

// CHECK-LABEL: func.func @serialize_double_buffer_x
// CHECK: %[[DBX0:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
// CHECK: xt.store(%[[DBX0]], %arg1, %{{.*}}, %{{.*}}) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
// CHECK: %[[DBX1:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
// CHECK: xt.store(%[[DBX1]], %arg1, %{{.*}}, %{{.*}}) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
// CHECK: xt.free(%[[DBX0]]) : tensor<16x16xf32>

// CHECK-LABEL: func.func @serialize_double_buffer_shared_x
// CHECK: %[[DBS0:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 1 : i64}
// CHECK: xt.store(%[[DBS0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[DBS0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: %[[DBS1:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 1 : i64}
// CHECK: xt.store(%[[DBS1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.free(%[[DBS0]]) : tensor<16x16xf32>
// CHECK: xt.store(%[[DBS1]], %arg1, %{{.*}}, %{{.*}})

// CHECK-LABEL: func.func @serialize_double_buffer_shared_xy
// CHECK: %[[DBZ0:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 2 : i64}
// CHECK: xt.store(%[[DBZ0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[DBZ0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[DBZ0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[DBZ0]], %arg1, %{{.*}}, %{{.*}})
// CHECK: %[[DBZ1:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) {shared = 2 : i64}
// CHECK: xt.store(%[[DBZ1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.free(%[[DBZ0]]) : tensor<16x16xf32>
// CHECK: xt.store(%[[DBZ1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[DBZ1]], %arg1, %{{.*}}, %{{.*}})
// CHECK: xt.store(%[[DBZ1]], %arg1, %{{.*}}, %{{.*}})

// CHECK-LABEL: func.func @serialize_double_buffer_store_value
// CHECK: %[[SVL0:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
// CHECK: %[[SVE0:.*]] = xt.exp(%[[SVL0]]) : tensor<16x16xf32> -> tensor<16x16xf32>
// CHECK: xt.store(%[[SVE0]], %arg1, %{{.*}}, %{{.*}}) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
// CHECK: %[[SVL1:.*]] = xt.load(%arg0, %{{.*}}, %{{.*}}) : (memref<128x16xf32>, i32, i32) -> tensor<16x16xf32>
// CHECK: %[[SVE1:.*]] = xt.exp(%[[SVL1]]) : tensor<16x16xf32> -> tensor<16x16xf32>
// CHECK: xt.store(%[[SVE1]], %arg1, %{{.*}}, %{{.*}}) : (tensor<16x16xf32>, memref<128x16xf32>, i32, i32) -> ()
// CHECK: xt.free(%[[SVE0]]) : tensor<16x16xf32>
